### ISSUE TITLE
VOXELFORMAT: VENGI: support loading and saving named points

### ISSUE THREAD

**Issue by mgerhardy** [vengi-voxel/vengi#470]
Formats like `3zh` have named point support and in general it would be nice to also export them to e.g. formats like gltf where game engines could make use of them for e.g. character hands and to place the items.

One idea would be a new scene graph node type called point and just give it a name, a coordinate and of course the transforms.

UFO:Alien Invasion was using tag files for this - as we also have md2 import support - maybe we could also import the tag files and the animation. But for getting of this done, the first step would be to get support for this into the format itself, import the points from formats like `3zh` and export them as point meshes to `gltf`

# Tasks

* [x] scenegraph node
* [x] vengi
* [x] 3zh
* [x] gltf
* [x] support in the editor

**Comment by BenMcLean** [comment]
One issue to watch out for is, in file formats which can contain multiple voxel models such as for animation frames, it should somehow be made clear that a named point is associated with one model/frame only. It shouldn't be possible to get confused which point belongs to which model/frame.

Also, the origin or "reference point" as VoxEdit's documentation calls this, should simply be one of the named points, with the name `Origin`. It should only special by convention, but not when parsing the file format.

**Comment by BenMcLean** [comment]
Another idea: It is valid for named points to be outside the bounds of the model. For example, a model of a character posed to throw an object might have a point outside the bounds of the model for where the object would land. It would be understandable if that's too hard for the editor to edit, but it should be valid for the file format.

My code's voxel models use three `ushort`s (unsigned 16-bit integers) for 3D coordinates and a byte for colors/materials, where 0 is empty and 1-255 are valid colors/materials. But my `Point3D` struct uses 32-bit signed integers because while it isn't valid to have voxels in negative coordinates, it is valid to have Points there.

**Comment by mgerhardy** [comment]
> Another idea: It is valid for named points to be outside the bounds of the model. For example, a model of a character posed to throw an object might have a point outside the bounds of the model for where the object would land after being thrown so the game engine can draw a target there. It would be understandable if that's too hard for the editor to edit, but it should be valid for whatever file format I adopt.
> 
> My code's voxel models use three `ushort`s (unsigned 16-bit integers) for 3D coordinates and a byte for colors/materials, where 0 is empty and 1-255 are valid colors/materials. But my `Point3D` struct uses 32-bit signed integers because while it isn't valid to have voxels in negative coordinates, it is valid to have points there.

This is already possible - the point can get moved free in the world already
